services:
  python:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.python.rule=Host(`idp.wrlc.localhost`)"
      - "traefik.http.routers.python.tls=true"
      - "traefik.http.routers.python.entrypoints=websecure"
    depends_on:
      - mysql
    networks:
      - proxy

  mysql:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8301:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - proxy

volumes:
    mysql-data:

networks:
  proxy:
    external: true
