services:
  wridp:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wridp.rule=Host(`idp.wrlc.localhost`)"
      - "traefik.http.routers.wridp.tls=true"
      - "traefik.http.routers.wridp.entrypoints=websecure"
    depends_on:
      - wridp_db
    networks:
      - proxy

  wridp_db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: wridp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - proxy

volumes:
    mysql-data:

networks:
  proxy:
    external: true
